format = """
$directory\
$git_branch\
$line_break\
$battery\
$character"""

add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](green)"

[git_branch]
format = "[git::$branch](purple)"


[git_status]
disabled = true

[directory]
style = "red"

[battery]
full_symbol = "ðŸ”‹"
charging_symbol = "ðŸ”Œ"
discharging_symbol = "âš¡"

