format = """
$directory\
$git_branch\
$line_break\
$battery\
$character"""

# add_newline = true

[character]
success_symbol = "[>](white)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](green)"

[git_branch]
format = "[\\[git:$branch\\]](green)"


[git_status]
disabled = true

[directory]
style = "#f659ed"
format='[pedro: ](red)[$path]($style)[$read_only]($read_only_style) '

[battery]
full_symbol = "ðŸ”‹"
charging_symbol = "ðŸ”Œ"
discharging_symbol = "âš¡"

